on:
  push:
    branches:
      - "*"

jobs:
  check-windows:
    name: Check Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare Rust
        run: rustup toolchain install stable --profile minimal

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "w2.rust"
          shared-key: "w2.rust"

      - name: Check
        run: cargo check -r

  check-linux:
    name: Check Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Install lib needed
      #   run: sudo apt-get install -y librust-atk-dev

      # - name: Prepare Rust
      #   run: rustup toolchain install stable --profile minimal

      - name: Install minimal
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "w2.rust"
          shared-key: "w2.rust"

      - name: Check
        run: cargo check -r
